### ISSUE TITLE
Dynamic tab removal not updating the layout.

### ISSUE THREAD

**Issue by saifim** [saddamakhtar88/MenuBarView#2]

**Comment by saddamakhtar88** [comment]
Are you calling setMenu() API to update the tabs?

**Comment by saifim** [comment]
Yes. I am calling setMenu() API.

**Comment by saddamakhtar88** [comment]
Hmm, I can reproduce it. 
I have made a minor change and released a new version 1.2.3
Give it a try and let me know if it helps.

**Comment by saifim** [comment]
Working fine now! Thanks for quick support.
